### ISSUE TITLE
Improve website

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/reason-react-native#341]
- [x] navbar
- [x] sidebar like on RN website
- [x] use odoc --fragment & use fragment as md files?
- [ ] ~~use docusaurus or something even more straight forward~~
- [x] use bs-rn itself for the website (dogfooding)
- [x] see if we want legacy docs or not
- [x] push online
- [x] sidebar show available & documented, available & undocumented, unavailable bindings
- [x] getting started doc
- [x] minimal example (template?)
- [x] blog
- [x] fix markdown issue (eg: anchor links)
- [x] add search via algolia docsearch (request made)

Any other ideas/comments would be appreciated.

**Comment by MoOx** [comment]
I am going to start something asap & as soon as I have a foundation I will open up new subtasks.

**Comment by MoOx** [comment]
New skeleton has landed. Probably more to come in the next few days.

**Comment by MoOx** [comment]
Algolia has been added :)

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/157534/59278923-46dc3b80-8c63-11e9-919c-d8fe167ad309.png">

**Comment by MoOx** [comment]
I want to add a schema for the intro doc.

Thoughts on this 2?

Quick version

<img width="655" alt="image" src="https://user-images.githubusercontent.com/157534/59389490-b3902c80-8d6e-11e9-804d-d80e1dc183a6.png">

Or more complete

<img width="652" alt="image" src="https://user-images.githubusercontent.com/157534/59389478-ac691e80-8d6e-11e9-950d-d9e35e1bac2c.png">

**Comment by MoOx** [comment]
I used the 2 version, improved a little. Feel free to discuss this idea :)

**Comment by abenoit** [comment]
I like the first one better because having arrows relating the logos looks more like a flow between all these technos. 
Just my humble opinion on that 😃

**Comment by cknitt** [comment]
Great work! I also like the first one better.

However, I think it should say "You get a safe React _Native_ app". Or just "You get a safer app" like in version 2.

**Comment by MoOx** [comment]
I have shipped the v1 modified a little (& used "You get a safer app")

**Comment by MoOx** [comment]
I will add a cheatsheet today. I guess we have a good website for a start :)

**Comment by dmartinjs** [comment]
it seams you will not use Docusaurus.

Is it possible to have an explanation about that, because it is used for documentations of Reason, Reason React and Buckelscript.

**Comment by MoOx** [comment]
dogfooding.

The website is build with react-native(-web) and the reason-react-native bindings.

Is that enough?

Any problem with the fact that we don't use Docusaurus?

**Comment by dmartinjs** [comment]
No problem.

I just wanted to know the reasons behind that choice 😉

**Comment by MoOx** [comment]
In short: it's more fun!
