### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/reason-react-native#344]
I like when things are short & simple so I will be brief

## Why a rewrite?

Current version is
- hard for new comers (rn/js dev learning reason)
- sometimes over-engineered
- bindings have a js cost on top of rn js

## How?

No "kaboom" release where everything have to be changed: idea is to be able to have 2 versions (packages or trick to have both) & slowly migrate over time: `BsReactNative` (legacy) + `ReactNative` (we go this way because why not - ReasonReact is going with `React`).

Monorepo will help with that: we are going to have a new folder for upcoming new version of the bindings.

@cknitt will bring back his work made in https://github.com/cca-io/cca-bs-react-native

---

# Current status

- [x] better migration script than official reason-react https://bloodyowl.github.io/blog/2019-04-19-an-alternative-migration-path-for-reason-react/
- [x] bs-react-native-jsx3-compat https://github.com/reasonml-community/bs-react-native/issues/413
- [x] reason-react-native works with reason-react 0.7.0 / reason jsx 3 (unreleased but usable from git, see readme)
- [x] blog post/doc for migration with example

**Comment by cknitt** [comment]
I will clean up / fix a few things in my repo first before bringing it into a v2 branch here.

**Comment by MoOx** [comment]
@cknitt with the current setup, we could work directly with small PRs into master as we are going to use another folder/new ns (check your DMs on Discord :) ). I am going to try to setup the following base folder with bs-platform 5, waiting patiently for your work in it.

**Comment by wokalski** [comment]
Great collaboration by you two @MoOx @cknitt

**Comment by MoOx** [comment]
Check out `bs-react-native-next` if you are curious. Stay tuned for public "release" (it's already usable with both current & next bindings (BsReactNative: current, ReactNative: next) if you use bs-platform 5.0.0 dev

**Comment by MoOx** [comment]
Reopening & pinned so people know what we are doing (see #348)

**Comment by MoOx** [comment]
I created a project that might help us to manage workload
https://github.com/reasonml-community/bs-react-native/projects/1

**Comment by MoOx** [comment]
I recently talked on discord about naming for new bindings but I am unsure about the strategy...

Here are possible solutions **that would allow people to slowly migrate**.
_Nobody can really offer the luxury of migrating an entire project with new reason-react hooks everywhere._

## 1. Use bs-react-native name for new bindings & move current to -legacy.

- bs-react-native-next => bs-react-native with ns ReactNative
- bs-react-native => bs-react-native-legacy with ns BsReactNative

People can just add the 2 packages, update bsconfig, & keep doing what they where doing & start using ReacNative + `[@bs.config {jsx: 3}]`.

This is kind of a HUGE breaking change for `bs-react-native` package, but at the end not that big as it's kind of moved to -legacy.
Might feel weird for end user.

## 2. Use reason-react-native for new bindings

- bs-react-native-next => reason-react-native with ns ReactNative
- bs-react-native with ns BsReactNative as it was + npm deprecate?

Same kind of experience here, people should be able to use both project at the same time, as soon as they use bs-p 5 + rr 0.7

## 3. Keep bs-react-native & nothing more

User should still be able to use old & new with [yarn alias feature](https://yarnpkg.com/en/docs/cli/add#toc-yarn-add-alias) but if they aren't using yarn, it will be problematic...

---

Chenglou told me he wanted to go away with reason- prefix because at the end, especially since it's zero-cost now, it's mainly just bucklescript features... So bs- make sense. He was talking about bringing the subject to reason conf, but it seems nothing has been discussed about that...

On the other hand we could stick to reason- to just match reason-react (& copy them if they change to something else). I found this solution maybe more straight forward for 2 reasons:

- we don't ask users to do weird stuff, they just add something new & use it
- it seems more accessible, especially to new comers: there is "reason" in the name, like reason-react.

Thoughts?

**Comment by cknitt** [comment]
Slight preference for 2 here (all three variants would work for me though).

**Comment by wokalski** [comment]
I think 2 is a good solution, too.

**Comment by MoOx** [comment]
Let's go for reason-react-native.

Here is how I see things:

- rename `bs-react-native-next` as `reason-react-native` asap
- rename repo to `reason-react-native` & keep old bindings in it (why? see below, for nice migration)
- (optional but I will handle it) create a `bs-react-native` repo just to keep old site up with redirection to the new one (https://reasonml-community.github.io/bs-react-native/ to `https://reasonml-community.github.io/reason-react-native/`)

Now how I see migration (at least for me):

1. migrate to bs-p 5 & rr 0.7 with jsx2 in bsconfig.json (level: easy, should cause any trouble to anyone)
2. migrate codebase to jsx3 in bsconfig.json
  2.1. (using official script for you components (spoiler) a better approach than wrapping all previous component (more on that in the next few days by somebody else)) (level: not fun, but could be easy with potential future solution)
  2.2 using a bs-react-native (legacy) bridge, migrated by us to jsx3 (level: easy, but not fun for us)
3. enjoy jsx3 & start using reason-react `React` name space with new reason-react-native `ReactNative`bindings if you want (at least at this stage, your codebase is ready for it)

If we handle the 2.2 migration (can handle it as I will be the first user), and if 2.1 upcoming solution see the sunlight (everybody pray with me), this could be done pretty easily for everyone, without too much pain.

Sounds good? Comments? Better ideas?

**Comment by MoOx** [comment]
Spoiler part 1 https://github.com/bloodyowl/reason-react-compat

**Comment by MoOx** [comment]
Spoiler part 2 https://github.com/bloodyowl/upgrade-reason-react

**Comment by MoOx** [comment]
Going to rename to reason-react-native since there is not open PR :) poke @cknitt @sgny

**Comment by MoOx** [comment]
Done. I will rename repo & website etc just before release :)

**Comment by MoOx** [comment]
Compat layer has been finished (but totally untested yet haha) https://github.com/reasonml-community/bs-react-native/pull/472

**Comment by MoOx** [comment]
If possible I would like to have reason-react-native & bs-react-native-jsx3-compat released tomorrow.
Doing my best to make things right today.

**Comment by MoOx** [comment]
Rewrite todo list is done. I just need to address a few thing for the website & release will be out.
I will probably cut the *publicly* release on monday next week (but should be ready before & probably on npm this weekend).

I will release reason-react-native as 0.60.0 unless someone doesn't agree (as discussed in #474)

**Comment by MoOx** [comment]
I have added some docs for intro & install & will try to have a minimal example & cheatsheet before release that I plan on monday.

**Comment by MoOx** [comment]
Release is here!

https://reasonml-community.github.io/reason-react-native/en/blog/2019-06-17-hello-reason-react-native/
