### ISSUE TITLE
Update template with reason-react-native

### ISSUE THREAD

**Issue by MoOx** [reasonml-community/reason-react-native#477]
It seems @dawee is on it according to discord.

@dawee raise the hand if you need help on this.

**Comment by dawee** [comment]
On the template not specially. I had this error on windows I told you about but for now I'm going to pu this aside and do my tests on my Linux machine.

**Comment by MoOx** [comment]
Do not hesitate to open a WIP PR if you want. I would like to have the template next week so we can start publising alpha of reason-react-native with the template that goes with it :)

**Comment by sgny** [comment]
@MoOx @dawee Should this (and its directory) be renamed `reason-react-native-template`?

**Comment by dawee** [comment]
> @MoOx @dawee Should this (and its directory) be renamed `reason-react-native-template`?

If I'm not mistaken I think `react-native init --template foo` is looking for a package with the prefix "react-native-template", so "react-native-template-foo". I think that's why it's called "react-native-template-reason", so you can call `react-native init --template reason`.

**Comment by sgny** [comment]
@dawee Thanks for the reply. I was hoping the directory could look neater. I wasn't aware of this detail (and I've never used a template), but you're right and there don't seem to be workarounds.

**Comment by MoOx** [comment]
We could name the folder `reason-react-native-template`, and keep  `react-native-template-reason` on npm (in the package.json), but maybe this will create more confusion that it brings as benefit?

**Comment by MoOx** [comment]
`react-native-template-reason` 0.2.0 is out :)

https://reasonml-community.github.io/reason-react-native/en/blog/2019-06-17-hello-reason-react-native/
